### ISSUE TITLE
Sorting / filtering results

### ISSUE THREAD

**Issue by mwarkentin** [rocketmiles/aws-cct#2]
It would be nice if you could sort and filter by the costs and deltas.

Example use cases:

* Sort services from most to least expensive (would need to figure out how to decide when looking at 2 months at once?)
* Show me only services which I spent > $1000 on
* Show me only services which increased or decreased in cost by at least $250
* Show me only services which increased or decreased in cost by at least 10% (ref #1)

**Comment by rgoomar** [comment]
This is now release in [v1.1.0](https://github.com/rocketmiles/aws-cct/releases/tag/v1.1.0)
